module.exports = {
  events: [
    {
      id: 1,
      name: "Metallica",
      date: "2024-06-28T00:00:00",
      image_url: "https://cdn.media.amplience.net/i/metallica/2024-06-12-fornite-x-metallica_carousel",
      created_at: "2024-05-27T00:00:00",
      available_spots: 10,
      price: 100
    },
    {
      id: 2,
      name: "The Weeknd",
      date: "2024-06-29T00:00:00",
      image_url: "https://cdn2.unrealengine.com/fortnite-festival-season-1-opening-night-the-weeknd-social-1920x1080-6d23697242d7.png",
      created_at: "2024-05-27T00:00:00",
      available_spots: 20,
      price: 200
    },
    {
      id: 3,
      name: "Eminem",
      date: "2024-06-30T00:00:00",
      image_url: "https://static01.nyt.com/images/2023/12/07/fashion/03fortnite-em/03fortnite-em-superJumbo.jpg",
      created_at: "2024-05-27T00:00:00",
      available_spots: 30,
      price: 300
    },
  ],
  spots: [
    {id: 1, name: "A1", status: 'available', event_id: 1},
    {id: 2, name: "A2", status: 'available', event_id: 1},
    {id: 3, name: "A3", status: 'available', event_id: 1},
    {id: 4, name: "A4", status: 'available', event_id: 1},
    {id: 5, name: "A5", status: 'available', event_id: 1},
    {id: 6, name: "B1", status: 'available', event_id: 1},
    {id: 7, name: "B2", status: 'available', event_id: 1},
    {id: 8, name: "B3", status: 'available', event_id: 1},
    {id: 9, name: "B4", status: 'available', event_id: 1},
    {id: 10, name: "B5", status: 'available', event_id: 1},

    {id: 1, name: "A1", status: 'available', event_id: 2},
    {id: 2, name: "A2", status: 'available', event_id: 2},
    {id: 3, name: "A3", status: 'available', event_id: 2},
    {id: 4, name: "A4", status: 'available', event_id: 2},
    {id: 5, name: "A5", status: 'available', event_id: 2},
    {id: 6, name: "A6", status: 'available', event_id: 2},
    {id: 7, name: "A7", status: 'available', event_id: 2},
    {id: 8, name: "A8", status: 'available', event_id: 2},
    {id: 9, name: "A9", status: 'available', event_id: 2},
    {id: 10, name: "A10", status: 'available', event_id: 2},
    {id: 11, name: "B1", status: 'available', event_id: 2},
    {id: 12, name: "B2", status: 'available', event_id: 2},
    {id: 13, name: "B3", status: 'available', event_id: 2},
    {id: 14, name: "B4", status: 'available', event_id: 2},
    {id: 15, name: "B5", status: 'available', event_id: 2},
    {id: 16, name: "B6", status: 'available', event_id: 2},
    {id: 17, name: "B7", status: 'available', event_id: 2},
    {id: 18, name: "B8", status: 'available', event_id: 2},
    {id: 19, name: "B9", status: 'available', event_id: 2},
    {id: 20, name: "B10", status: 'available', event_id: 2},

    {id: 1, name: "A1", status: 'available', event_id: 3},
    {id: 2, name: "A2", status: 'available', event_id: 3},
    {id: 3, name: "A3", status: 'available', event_id: 3},
    {id: 4, name: "A4", status: 'available', event_id: 3},
    {id: 5, name: "A5", status: 'available', event_id: 3},
    {id: 6, name: "A6", status: 'available', event_id: 3},
    {id: 7, name: "A7", status: 'available', event_id: 3},
    {id: 8, name: "A8", status: 'available', event_id: 3},
    {id: 9, name: "A9", status: 'available', event_id: 3},
    {id: 10, name: "A10", status: 'available', event_id: 3},
    {id: 11, name: "A11", status: 'available', event_id: 3},
    {id: 12, name: "A12", status: 'available', event_id: 3},
    {id: 13, name: "A13", status: 'available', event_id: 3},
    {id: 14, name: "A14", status: 'available', event_id: 3},
    {id: 15, name: "A15", status: 'available', event_id: 3},
    {id: 16, name: "B1", status: 'available', event_id: 3},
    {id: 17, name: "B2", status: 'available', event_id: 3},
    {id: 18, name: "B3", status: 'available', event_id: 3},
    {id: 19, name: "B4", status: 'available', event_id: 3},
    {id: 20, name: "B5", status: 'available', event_id: 3},
    {id: 21, name: "B6", status: 'available', event_id: 3},
    {id: 22, name: "B7", status: 'available', event_id: 3},
    {id: 23, name: "B8", status: 'available', event_id: 3},
    {id: 24, name: "B9", status: 'available', event_id: 3},
    {id: 25, name: "B10", status: 'available', event_id: 3},
    {id: 26, name: "B11", status: 'available', event_id: 3},
    {id: 27, name: "B12", status: 'available', event_id: 3},
    {id: 28, name: "B13", status: 'available', event_id: 3},
    {id: 29, name: "B14", status: 'available', event_id: 3},
    {id: 30, name: "B15", status: 'available', event_id: 3},
  ]
}